---
- name: Update Windows machines
  hosts: windows
  gather_facts: false
  tasks:
    - name: Check for updates
      win_updates:
        category_names: ['SecurityUpdates']
        state: 'installed'

    - name: Install updates
      win_updates:
        category_names: ['SecurityUpdates']
        state: 'present'
